"""initial schema

Revision ID: ef946693af9d
Revises: 
Create Date: 2026-09-04 06:06:51.568114

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'ef946693af9d'
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_users'))
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', 'id', name=op.f('pk_app_settings'))
    )
    op.create_table('audit_logs',
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=120), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_table('automation_logs',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('job_name', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('items_processed', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automation_logs'))
    )
    op.create_index(op.f('ix_automation_logs_job_name'), 'automation_logs', ['job_name'], unique=False)
    op.create_index(op.f('ix_automation_logs_run_id'), 'automation_logs', ['run_id'], unique=False)
    op.create_table('caption_templates',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('template_text', sa.Text(), nullable=False),
    sa.Column('placeholder_keys', sa.JSON(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_caption_templates'))
    )
    op.create_table('captions',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('hashtags', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_captions'))
    )
    op.create_table('content_sources',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('authorization', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('categories', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('check_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_sources'))
    )
    op.create_table('error_logs',
    sa.Column('scope', sa.String(length=80), nullable=False),
    sa.Column('error_type', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('traceback', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_error_logs'))
    )
    op.create_index(op.f('ix_error_logs_scope'), 'error_logs', ['scope'], unique=False)
    op.create_table('publishing_batches',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('jobs_total', sa.Integer(), nullable=False),
    sa.Column('jobs_done', sa.Integer(), nullable=False),
    sa.Column('jobs_failed', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rest_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publishing_batches'))
    )
    op.create_index(op.f('ix_publishing_batches_status'), 'publishing_batches', ['status'], unique=False)
    op.create_table('reel_covers',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reel_covers'))
    )
    op.create_table('schedules',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('applies_to', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedules'))
    )
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('destination_accounts',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('automation_enabled', sa.Boolean(), nullable=False),
    sa.Column('integration_status', sa.String(length=30), nullable=False),
    sa.Column('credentials_enc', sa.Text(), nullable=False),
    sa.Column('profile_pic_url', sa.Text(), nullable=False),
    sa.Column('followers_count', sa.BigInteger(), nullable=False),
    sa.Column('last_publish_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('default_caption_id', sa.Integer(), nullable=True),
    sa.Column('caption_template_id', sa.Integer(), nullable=True),
    sa.Column('reel_cover_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caption_template_id'], ['caption_templates.id'], name=op.f('fk_destination_accounts_caption_template_id_caption_templates')),
    sa.ForeignKeyConstraint(['default_caption_id'], ['captions.id'], name=op.f('fk_destination_accounts_default_caption_id_captions')),
    sa.ForeignKeyConstraint(['reel_cover_id'], ['reel_covers.id'], name=op.f('fk_destination_accounts_reel_cover_id_reel_covers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_destination_accounts'))
    )
    op.create_table('rss_feeds',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('feed_name', sa.String(length=160), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('check_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('etag', sa.String(length=255), nullable=False),
    sa.Column('last_modified', sa.String(length=255), nullable=False),
    sa.Column('items_seen', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['content_sources.id'], name=op.f('fk_rss_feeds_source_id_content_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rss_feeds'))
    )
    op.create_index(op.f('ix_rss_feeds_source_id'), 'rss_feeds', ['source_id'], unique=True)
    op.create_table('account_metrics',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('followers', sa.BigInteger(), nullable=False),
    sa.Column('following', sa.BigInteger(), nullable=False),
    sa.Column('posts_count', sa.BigInteger(), nullable=False),
    sa.Column('views', sa.BigInteger(), nullable=False),
    sa.Column('likes', sa.BigInteger(), nullable=False),
    sa.Column('comments', sa.BigInteger(), nullable=False),
    sa.Column('shares', sa.BigInteger(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['destination_accounts.id'], name=op.f('fk_account_metrics_account_id_destination_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_metrics'))
    )
    op.create_index(op.f('ix_account_metrics_account_id'), 'account_metrics', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_metrics_captured_at'), 'account_metrics', ['captured_at'], unique=False)
    op.create_table('account_settings',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('caption_settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('cover_settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('schedule_settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('posting_limits', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('distribution', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['destination_accounts.id'], name=op.f('fk_account_settings_account_id_destination_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_settings'))
    )
    op.create_index(op.f('ix_account_settings_account_id'), 'account_settings', ['account_id'], unique=True)
    op.create_table('daily_metrics',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('followers', sa.BigInteger(), nullable=False),
    sa.Column('new_followers', sa.BigInteger(), nullable=False),
    sa.Column('posts', sa.BigInteger(), nullable=False),
    sa.Column('views', sa.BigInteger(), nullable=False),
    sa.Column('likes', sa.BigInteger(), nullable=False),
    sa.Column('comments', sa.BigInteger(), nullable=False),
    sa.Column('shares', sa.BigInteger(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['destination_accounts.id'], name=op.f('fk_daily_metrics_account_id_destination_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_metrics')),
    sa.UniqueConstraint('account_id', 'date', name='uq_daily_account_date')
    )
    op.create_index(op.f('ix_daily_metrics_account_id'), 'daily_metrics', ['account_id'], unique=False)
    op.create_index(op.f('ix_daily_metrics_date'), 'daily_metrics', ['date'], unique=False)
    op.create_table('discovered_content',
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('rss_feed_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('media_url', sa.Text(), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('target_account_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rss_feed_id'], ['rss_feeds.id'], name=op.f('fk_discovered_content_rss_feed_id_rss_feeds')),
    sa.ForeignKeyConstraint(['source_id'], ['content_sources.id'], name=op.f('fk_discovered_content_source_id_content_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discovered_content'))
    )
    op.create_index(op.f('ix_discovered_content_category'), 'discovered_content', ['category'], unique=False)
    op.create_index(op.f('ix_discovered_content_discovered_at'), 'discovered_content', ['discovered_at'], unique=False)
    op.create_index(op.f('ix_discovered_content_external_id'), 'discovered_content', ['external_id'], unique=False)
    op.create_index(op.f('ix_discovered_content_source_id'), 'discovered_content', ['source_id'], unique=False)
    op.create_index(op.f('ix_discovered_content_status'), 'discovered_content', ['status'], unique=False)
    op.create_index(op.f('ix_discovered_content_url'), 'discovered_content', ['url'], unique=False)
    op.create_table('reports',
    sa.Column('report_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['destination_accounts.id'], name=op.f('fk_reports_account_id_destination_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_report_type'), 'reports', ['report_type'], unique=False)
    op.create_table('trend_history',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('engagement', sa.Float(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['discovered_content.id'], name=op.f('fk_trend_history_content_id_discovered_content')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trend_history'))
    )
    op.create_index(op.f('ix_trend_history_captured_at'), 'trend_history', ['captured_at'], unique=False)
    op.create_index(op.f('ix_trend_history_content_id'), 'trend_history', ['content_id'], unique=False)
    op.create_table('trend_scores',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('signals', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('engine_version', sa.String(length=20), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['discovered_content.id'], name=op.f('fk_trend_scores_content_id_discovered_content')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trend_scores'))
    )
    op.create_index(op.f('ix_trend_scores_content_id'), 'trend_scores', ['content_id'], unique=True)
    op.create_table('videos',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('original_path', sa.Text(), nullable=False),
    sa.Column('cover_path', sa.Text(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('fps', sa.Float(), nullable=False),
    sa.Column('has_audio', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['discovered_content.id'], name=op.f('fk_videos_content_id_discovered_content')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_videos'))
    )
    op.create_index(op.f('ix_videos_content_id'), 'videos', ['content_id'], unique=False)
    op.create_index(op.f('ix_videos_status'), 'videos', ['status'], unique=False)
    op.create_table('publishing_jobs',
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('caption_id', sa.Integer(), nullable=True),
    sa.Column('cover_id', sa.Integer(), nullable=True),
    sa.Column('caption_text', sa.Text(), nullable=False),
    sa.Column('job_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('publish_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['destination_accounts.id'], name=op.f('fk_publishing_jobs_account_id_destination_accounts')),
    sa.ForeignKeyConstraint(['batch_id'], ['publishing_batches.id'], name=op.f('fk_publishing_jobs_batch_id_publishing_batches')),
    sa.ForeignKeyConstraint(['caption_id'], ['captions.id'], name=op.f('fk_publishing_jobs_caption_id_captions')),
    sa.ForeignKeyConstraint(['content_id'], ['discovered_content.id'], name=op.f('fk_publishing_jobs_content_id_discovered_content')),
    sa.ForeignKeyConstraint(['cover_id'], ['reel_covers.id'], name=op.f('fk_publishing_jobs_cover_id_reel_covers')),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_publishing_jobs_video_id_videos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publishing_jobs'))
    )
    op.create_index(op.f('ix_publishing_jobs_account_id'), 'publishing_jobs', ['account_id'], unique=False)
    op.create_index(op.f('ix_publishing_jobs_batch_id'), 'publishing_jobs', ['batch_id'], unique=False)
    op.create_index(op.f('ix_publishing_jobs_content_id'), 'publishing_jobs', ['content_id'], unique=False)
    op.create_index(op.f('ix_publishing_jobs_publish_at'), 'publishing_jobs', ['publish_at'], unique=False)
    op.create_index(op.f('ix_publishing_jobs_status'), 'publishing_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_publishing_jobs_video_id'), 'publishing_jobs', ['video_id'], unique=False)
    op.create_table('video_hashes',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('phash', sa.Text(), nullable=False),
    sa.Column('phash_frames', sa.Integer(), nullable=False),
    sa.Column('source_url_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_video_hashes_video_id_videos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_video_hashes'))
    )
    op.create_index(op.f('ix_video_hashes_sha256'), 'video_hashes', ['sha256'], unique=False)
    op.create_index(op.f('ix_video_hashes_source_url_hash'), 'video_hashes', ['source_url_hash'], unique=False)
    op.create_index(op.f('ix_video_hashes_video_id'), 'video_hashes', ['video_id'], unique=False)
    op.create_table('analytics',
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['destination_accounts.id'], name=op.f('fk_analytics_account_id_destination_accounts')),
    sa.ForeignKeyConstraint(['content_id'], ['discovered_content.id'], name=op.f('fk_analytics_content_id_discovered_content')),
    sa.ForeignKeyConstraint(['job_id'], ['publishing_jobs.id'], name=op.f('fk_analytics_job_id_publishing_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics'))
    )
    op.create_index(op.f('ix_analytics_account_id'), 'analytics', ['account_id'], unique=False)
    op.create_index(op.f('ix_analytics_content_id'), 'analytics', ['content_id'], unique=False)
    op.create_index(op.f('ix_analytics_event_type'), 'analytics', ['event_type'], unique=False)
    op.create_index(op.f('ix_analytics_job_id'), 'analytics', ['job_id'], unique=False)
    op.create_index(op.f('ix_analytics_occurred_at'), 'analytics', ['occurred_at'], unique=False)
    op.create_table('publishing_history',
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('external_post_id', sa.String(length=255), nullable=False),
    sa.Column('permalink', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['destination_accounts.id'], name=op.f('fk_publishing_history_account_id_destination_accounts')),
    sa.ForeignKeyConstraint(['content_id'], ['discovered_content.id'], name=op.f('fk_publishing_history_content_id_discovered_content')),
    sa.ForeignKeyConstraint(['job_id'], ['publishing_jobs.id'], name=op.f('fk_publishing_history_job_id_publishing_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publishing_history'))
    )
    op.create_index(op.f('ix_publishing_history_account_id'), 'publishing_history', ['account_id'], unique=False)
    op.create_index(op.f('ix_publishing_history_content_id'), 'publishing_history', ['content_id'], unique=False)
    op.create_index(op.f('ix_publishing_history_job_id'), 'publishing_history', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publishing_history_job_id'), table_name='publishing_history')
    op.drop_index(op.f('ix_publishing_history_content_id'), table_name='publishing_history')
    op.drop_index(op.f('ix_publishing_history_account_id'), table_name='publishing_history')
    op.drop_table('publishing_history')
    op.drop_index(op.f('ix_analytics_occurred_at'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_job_id'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_event_type'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_content_id'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_account_id'), table_name='analytics')
    op.drop_table('analytics')
    op.drop_index(op.f('ix_video_hashes_video_id'), table_name='video_hashes')
    op.drop_index(op.f('ix_video_hashes_source_url_hash'), table_name='video_hashes')
    op.drop_index(op.f('ix_video_hashes_sha256'), table_name='video_hashes')
    op.drop_table('video_hashes')
    op.drop_index(op.f('ix_publishing_jobs_video_id'), table_name='publishing_jobs')
    op.drop_index(op.f('ix_publishing_jobs_status'), table_name='publishing_jobs')
    op.drop_index(op.f('ix_publishing_jobs_publish_at'), table_name='publishing_jobs')
    op.drop_index(op.f('ix_publishing_jobs_content_id'), table_name='publishing_jobs')
    op.drop_index(op.f('ix_publishing_jobs_batch_id'), table_name='publishing_jobs')
    op.drop_index(op.f('ix_publishing_jobs_account_id'), table_name='publishing_jobs')
    op.drop_table('publishing_jobs')
    op.drop_index(op.f('ix_videos_status'), table_name='videos')
    op.drop_index(op.f('ix_videos_content_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_trend_scores_content_id'), table_name='trend_scores')
    op.drop_table('trend_scores')
    op.drop_index(op.f('ix_trend_history_content_id'), table_name='trend_history')
    op.drop_index(op.f('ix_trend_history_captured_at'), table_name='trend_history')
    op.drop_table('trend_history')
    op.drop_index(op.f('ix_reports_report_type'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_discovered_content_url'), table_name='discovered_content')
    op.drop_index(op.f('ix_discovered_content_status'), table_name='discovered_content')
    op.drop_index(op.f('ix_discovered_content_source_id'), table_name='discovered_content')
    op.drop_index(op.f('ix_discovered_content_external_id'), table_name='discovered_content')
    op.drop_index(op.f('ix_discovered_content_discovered_at'), table_name='discovered_content')
    op.drop_index(op.f('ix_discovered_content_category'), table_name='discovered_content')
    op.drop_table('discovered_content')
    op.drop_index(op.f('ix_daily_metrics_date'), table_name='daily_metrics')
    op.drop_index(op.f('ix_daily_metrics_account_id'), table_name='daily_metrics')
    op.drop_table('daily_metrics')
    op.drop_index(op.f('ix_account_settings_account_id'), table_name='account_settings')
    op.drop_table('account_settings')
    op.drop_index(op.f('ix_account_metrics_captured_at'), table_name='account_metrics')
    op.drop_index(op.f('ix_account_metrics_account_id'), table_name='account_metrics')
    op.drop_table('account_metrics')
    op.drop_index(op.f('ix_rss_feeds_source_id'), table_name='rss_feeds')
    op.drop_table('rss_feeds')
    op.drop_table('destination_accounts')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('schedules')
    op.drop_table('reel_covers')
    op.drop_index(op.f('ix_publishing_batches_status'), table_name='publishing_batches')
    op.drop_table('publishing_batches')
    op.drop_index(op.f('ix_error_logs_scope'), table_name='error_logs')
    op.drop_table('error_logs')
    op.drop_table('content_sources')
    op.drop_table('captions')
    op.drop_table('caption_templates')
    op.drop_index(op.f('ix_automation_logs_run_id'), table_name='automation_logs')
    op.drop_index(op.f('ix_automation_logs_job_name'), table_name='automation_logs')
    op.drop_table('automation_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('app_settings')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
